### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by Carlosjavierarizaperez** [piekarskipiotr/flutter-nude-detector#3]
**Does not load model **

Do not load the file nude.tflite even if it is in assets, it does not read it..

**Comment by piekarskipiotr** [comment]
Can you provide your folder structure view where you put nude.tflite and your pubspec.yaml?

**Comment by Carlosjavierarizaperez** [comment]
![image](https://github.com/piekarskipiotr/flutter-nude-detector/assets/97035752/2236ad36-e150-4cbb-8571-f4b448ff0f80)

But I tried it with another lib and it works.

**Comment by piekarskipiotr** [comment]
Please follow the installation steps: https://github.com/piekarskipiotr/flutter-nude-detector#installation
Default path to nude.tflite should be assets/ml_models/
